### ISSUE TITLE
exception "struct.error: 'H' format requires 0 <= number <= 65535" during block processing

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/electrumx#19] opened 2019-10-18 09:32 UTC
```
@400000005da97e4a08284b84 ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /home/nick/electronx/electrumx/server/controller.py:81> exception=error("'H' format requires 0 <= number <= 65535",)>
@400000005da97e4a08285354 Traceback (most recent call last):
@400000005da97e4a0828573c   File "/usr/local/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
@400000005da97e4a08285b24     task.result()
@400000005da97e4a08285b24   File "/home/nick/electronx/electrumx/server/controller.py", line 134, in serve
@400000005da97e4a08288dec     await group.spawn(wait_for_catchup())
@400000005da97e4a082891d4   File "/usr/local/lib/python3.6/site-packages/aiorpcx/curio.py", line 238, in __aexit__
@400000005da97e4a082895bc     await self.join()
@400000005da97e4a082895bc   File "/usr/local/lib/python3.6/site-packages/aiorpcx/curio.py", line 207, in join
@400000005da97e4a082899a4     raise task.exception()
@400000005da97e4a082899a4   File "/home/nick/electronx/electrumx/server/block_processor.py", line 667, in fetch_and_process_blocks
@400000005da97e4a0828ad2c     await self.flush(True)
@400000005da97e4a0828b114   File "/home/nick/electronx/electrumx/server/block_processor.py", line 335, in flush
@400000005da97e4a0828b4fc     await self.run_in_thread_with_lock(flush)
@400000005da97e4a0828b4fc   File "/home/nick/electronx/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
@400000005da97e4a08290ed4     return await asyncio.shield(run_in_thread_locked())
@400000005da97e4a08290ed4   File "/home/nick/electronx/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
@400000005da97e4a082912bc     return await run_in_thread(func, *args)
@400000005da97e4a082916a4   File "/usr/local/lib/python3.6/site-packages/aiorpcx/curio.py", line 68, in run_in_thread
@400000005da97e4a08292644     return await get_event_loop().run_in_executor(None, func, *args)
@400000005da97e4a08292a2c   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
@400000005da97e4a08292e14     result = self.fn(*self.args, **self.kwargs)
@400000005da97e4a082931fc   File "/home/nick/electronx/electrumx/server/block_processor.py", line 334, in flush
@400000005da97e4a082931fc     self.estimate_txs_remaining)
@400000005da97e4a08293db4   File "/home/nick/electronx/electrumx/server/db.py", line 200, in flush_dbs
@400000005da97e4a0829419c     self.flush_history()
@400000005da97e4a08294584   File "/home/nick/electronx/electrumx/server/db.py", line 269, in flush_history
@400000005da97e4a08294584     self.history.flush()
@400000005da97e4a0829496c   File "/home/nick/electronx/electrumx/server/history.py", line 128, in flush
@400000005da97e4a08294d54     flush_id = pack_be_uint16(self.flush_count)
@400000005da97e4a0829590c struct.error: 'H' format requires 0 <= number <= 65535
@400000005da985fb0b519b1c WARNING:Controller:received SIGTERM signal, initiating shutdown
```

this is on current master branch

on restart it continues processing blocks fine. the exception happened 2 times so far while processing around 10000 blocks (rough guess)

**Comment by cculianu** [comment] 2019-10-18 12:02
Can you go back and try the released version? I believe a commit that mark lundeberg added may be responsible.

Try it and let me know.. maybe you can restart the block processing if you really want to be helpful .. and let me know if it happens.

Released version here: https://github.com/Electron-Cash/electrumx/releases/tag/1.10.1

Or you can do: `git checkout 1.10.1`

**Comment by molecular** [comment] 2019-10-18 16:07
@cculianu 

> Try it and let me know.. maybe you can restart the block processing if you really want to be helpful

no need to restart, it happened another 5 or so times. Still 10985 blocks to go.

checked out 1.10.1 and restarted... now I wait

**Comment by molecular** [comment] 2019-10-18 16:10
just noticed it kept picking up at the same point, so no progress was actually done by my repeatedly restarting. Let's see if 1.10.1 can get past that point

**Comment by cculianu** [comment] 2019-10-18 16:13
Do let me know. I am suspicious of a change that happened recently as it went in seemingly without much thought.  If it doesn't crash I'm reverting the commit that I am suspicious of.

**Comment by molecular** [comment] 2019-10-18 16:50
still crashes with 1.10.1 :-(

If you want to get to the bottom of this I'm happy to help any way I can.

**Comment by molecular** [comment] 2019-10-18 16:54
out of interest: did you suspect this change: 1b536bae51f4d205d7279795e751d1a28d28d4f8

**Comment by cculianu** [comment] 2019-10-18 16:54
Yeah.. because it was added after release and I didn't really understand what it did... lol

**Comment by cculianu** [comment] 2019-10-18 16:55
Hmm. I wonder if at this point your block DB is corrupted and it would crash anyway.  Is there any way you can try from scratch (that is, blow away the ELECTRUM_DB dir and restart)?

Maybe with 1.10.1, starting from scratch.. it will work?

**Comment by molecular** [comment] 2019-10-18 16:57
yeah, I'll try that

**Comment by cculianu** [comment] 2019-10-18 16:59
Thanks man this is a big help. 👍

**Comment by molecular** [comment] 2019-10-18 17:01
no problem. will report back, ETA is 18 hours, though. Damn I should updgrade that hardware.

**Comment by cculianu** [comment] 2019-10-18 17:06
Oh wow. Is it an HD?

Did you check if it has disk sector errors using smartmontools?  It could just be corruption on the disk too.. sadly...

But yeah keep me posted on what happens.

**Comment by cculianu** [comment] 2019-10-18 17:12
Ok.. I'm reading the code. ~~I'm like 95% sure that commit 1b536ba is causing this problem~~.

~~The problem is that commit makes it flush so often that it loops pas the 16-bit integer used to store the flush count.. so that's why it breaks.~~

~~Yeah I am pretty sure now you should not be experiencing any problems.~~

**Comment by cculianu** [comment] 2019-10-18 17:13
Oh no wait.. my bad. I'm only 10% sure. I'm curious what happens now. LMK

**Comment by cculianu** [comment] 2019-10-18 17:14
Can you paste in relevant parts of your env file that you used to start electrumx?

Maybe there's something in your env causing it to flush too often?

**Comment by molecular** [comment] 2019-10-18 17:26
```
root@nil /service/electrumx_abc/env # cd /service/electrumx_abc/env/ && for f in $(ls); do echo -e "\n"$f; cat $f; done

ANON_LOGS
anon

BANNER_FILE
/home/electrumx/db_abc/banner.txt

COIN
BitcoinCash

DAEMON_URL
http://bitcoinrpc:<hidden>@127.0.0.1:8332

DB_DIRECTORY
/home/electrumx/db_abc

ELECTRUMX
/home/nick/electronx/electrumx_server.py

HOST
electrum-abc.criptolayer.net


MAX_SESSIONS
3000

NET
mainnet

REORG_LIMIT
504

REPORT_HOST
electrum-abc.criptolayer.net

RPC_PORT
8022

SSL_CERTFILE
/etc/ssl/electrumx/electrum_abc.criptolayer.net.crt

SSL_KEYFILE
/etc/ssl/electrumx/electrum_abc.criptolayer.net.key

SSL_PORT
50012

USERNAME
electrumx
```

**Comment by cculianu** [comment] 2019-10-18 17:27
Nothing suspicious there. Thanks for posting. Darn. :/

I really really wonder what is up. The joys of supporting code you didn't write...

**Comment by molecular** [comment] 2019-10-18 17:28
I just noticed I had ELECTRUMX still pointing to the old electrUMx code. Just interrupted the sync, switched back the old (possibly corrupt) db directory and will see wether that makes a difference.

**Comment by molecular** [comment] 2019-10-18 17:28
how on earth are you responding so quickly? you have like a chat-style frontend to github or something?

**Comment by cculianu** [comment] 2019-10-18 17:28
It just pops up immediately whenever it changes..

lol

**Comment by cculianu** [comment] 2019-10-18 17:29
We should take this to chat -- are you in the Electron Cash telegram channel?

**Comment by cculianu** [comment] 2019-10-18 17:47
Known bug upstream: https://github.com/kyuupichan/electrumx/issues/185

**Comment by markblundeberg** [comment] 2019-10-18 17:47
> I'm like 95% sure that commit [1b536ba](https://github.com/Electron-Cash/electrumx/commit/1b536bae51f4d205d7279795e751d1a28d28d4f8) is causing this problem.

me program bad? T_T

**Comment by cculianu** [comment] 2019-10-18 17:48
@markblundeberg No.. i misunderstood what your code did. I thought it affected writes. It doesn't. Your code not causing this. Sorry. My bad.

**Comment by markblundeberg** [comment] 2019-10-18 17:49
Hehe yeah no worries. =D

**Comment by molecular** [comment] 2019-10-18 21:46
ok, this fixed it for me:

```
#> export DB_DIRECTORY=<electrumx db dir>
#> export COIN=BitcoinCash
#> ./electrumx_compact_history
```

thanks to @cculianu for tipping me off to this

background info in upstream issue: https://github.com/kyuupichan/electrumx/issues/185

**Comment by cculianu** [comment] 2020-03-25 09:12
This fork has been discontinued so I am closing this thread.  ElectrumX still has this problem but Fulcrum does not.  I recommend you install Fulcrum to avoid this inconvenience.  See issue #20.

**Closed as completed by cculianu** 2020-03-25 09:12 UTC
Labels: bug
